### ISSUE TITLE
remove points layer for hospitalization forecasts 

### ISSUE THREAD

**Issue by nickreich** [reichlab/Covid-19-Hub-Vizualization#45]
Ensemble hospitalization forecasts with only 14 days ahead show points. The forecasts with 28 days show just a line. For consistency, I think the ensemble forecast should be just the line. If there is an adjustable threshold for how many "steps ahead" to show before not showing points, I think it should be set at 7.

**Comment by vrushti-mody** [comment]
I can change the code so that all points are
