### ISSUE TITLE
add process for incorporating late models

### ISSUE THREAD

**Issue by nickreich** [reichlab/Covid-19-Hub-Vizualization#77]
e.g. The JHUAPL-SLPHospEns model is submitted every week to the hub, but they often miss the 8am deadline on Tuesday morning for submissions of ensembles to be included in the visualization build.  It appears that then those forecasts are not added in subsequent weeks. Is there a simple fix to ensure that forecasts like this, that are validly submitted after we update the viz, are included in future weeks?

**Comment by nickreich** [comment]
Note that I think this is also the case for the COVIDhub_CDC-ensemble model sometimes.

**Comment by elray1** [comment]
@vrushti-mody just noting that we had said we'd update the github action for forecast updates to run on Wed mornings
