### ISSUE TITLE
In preprocess_forecasts, replace use of covidEnsembles::load_covid_forecasts_relative_horizon

### ISSUE THREAD

**Issue by elray1** [reichlab/Covid-19-Hub-Vizualization#79]
We can eliminate a dependency on covidEnsembles by replacing the call to `covidEnsembles::load_covid_forecasts_relative_horizon` [here](https://github.com/reichlab/Covid-19-Hub-Vizualization/blob/e28d5845dd98367a2761f96a7e3b52d71d3a3918/preprocess_data/preprocess_forecasts.R#L113-L126) with calls to `covidHubUtils::load_forecasts` and `covidHubUtils::align_forecasts`.

**Comment by elray1** [comment]
While we're at it, we could replace the term `"as_of"` with `"ref_date"` in this `preprocess_forecasts.R` script.  (There is no need to change this terminology anywhere else for right now.)

**Comment by aaronger** [comment]
https://github.com/reichlab/Covid-19-Hub-Vizualization/pull/86
